### PR TITLE
feat: Support git shallow clone

### PR DESCRIPTION
**Pull request by Filbird**
## Context
Repositories containing huge commit trees take noticeably longer to clone. In most use cases the entire commit tree is not needed in a Screwdriver job. As such, we can make use of git shallow cloning to only clone a subset of the commit tree and thus improve performance.

## Objectives
- Enable git shallow cloning with a default depth of 50.
- Allow users to opt out by setting the environment variable `GIT_SHALLOW_CLONE` to `false`

## References
https://github.com/screwdriver-cd/screwdriver/projects/4#card-14436792

### CODE REVIEW

**Comment by minz1027** [comment]
why this is opt out but not opt in? Is it possible that it breaks some current user?

**Comment by jithin1987** [comment]
@minz1027 
> why this is opt out but not opt in? Is it possible that it breaks some current user? 

I think we should default to performant way, and slower approach should be opt in.

**Comment by minz1027** [comment]
we should probably document this behavior in the guide.

**Comment by Filbird** [comment]
Good idea, will do!

**Pull request merged**
